<?php

namespace App\Exports;

use App\Imports\MembersImport;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;

/**
 * Downloadable import template for members. The heading row matches exactly the
 * keys expected by {@see MembersImport}, and one example row shows
 * the valid value formats so users don't fill the file incorrectly.
 *
 * `member_number` is intentionally NOT a column — it is always generated by the
 * system (D2).
 */
class MembersTemplateExport implements FromArray, ShouldAutoSize, WithHeadings, WithTitle
{
    /**
     * @return array<int, string>
     */
    public function headings(): array
    {
        return [
            'nik',
            'nama',
            'nip',
            'kode_opd',
            'kode_golongan',
            'tempat_lahir',
            'tanggal_lahir',
            'jenis_kelamin',
            'jabatan',
            'status_kepegawaian',
            'no_rekening_gaji',
            'nama_bank',
            'alamat',
            'no_hp',
            'tanggal_bergabung',
            'nama_ahli_waris',
            'hubungan_ahli_waris',
            'no_hp_ahli_waris',
            'status',
            'simpanan_wajib',
        ];
    }

    /**
     * One example row + one hint row documenting the allowed values.
     *
     * @return array<int, array<int, string>>
     */
    public function array(): array
    {
        return [
            [
                '3201234567890001',
                'Budi Santoso',
                '199001012020121001',
                'OPD0001',
                'GOL-1',
                'Semarang',
                '1990-01-01',
                'L',
                'Staf',
                'ASN',
                '1234567890',
                'BRI',
                'Jl. Merdeka No. 1',
                '081234567890',
                '2026-01-01',
                'Siti',
                'Istri',
                '081298765432',
                'Aktif',
                '50000',
            ],
            [
                'NIK 16 digit unik',
                'wajib',
                'wajib utk ASN',
                'kode OPD terdaftar',
                'kode golongan terdaftar',
                'wajib',
                'YYYY-MM-DD',
                'L atau P',
                'opsional',
                'ASN atau Honorer',
                'wajib',
                'opsional',
                'wajib',
                'tanpa 0 depan',
                'YYYY-MM-DD',
                'wajib',
                'Istri/Suami/Anak/Orang Tua/Saudara Kandung/Lainnya',
                'wajib',
                'Aktif/Non-Aktif/Keluar/Meninggal',
                'opsional, default dari golongan',
            ],
        ];
    }

    public function title(): string
    {
        return 'Template Anggota';
    }
}
